line = expr, {multiply, expr};
expr = perm, cycle, {cycle}, power;
perm = 'perm';
space = ' ';
cycle = '(', number, {space, number}, ')';
multiply = '*';
number = firstdigit, {digit};
digit = ’0’ | ’1’ | ’2’ | ’3’ | ’4’ | ’5’ | ’6’ | ’7’ | ’8’ | ’9’;
firstdigit = ’1’ | ’2’ | ’3’ | ’4’ | ’5’ | ’6’ | ’7’ | ’8’ | ’9’;
minus = '-' |;
power = '^', minus, number |;